### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by pmorerio** [GRAAL-Research/domain_adversarial_neural_network#2]
Hi, 
first of all thanks for sharing your code. I was trying to reproduce the results presented in the paper for the _Amazon_ experiment, but I realized that when setting `lambda=0.0` and/or `adversarial_representation=False` the numerical results for the risk do not change _at all_. 

`adversarial_representation=True` 
![image](https://cloud.githubusercontent.com/assets/6783835/20518197/882e440a-b09e-11e6-98e7-ac479a5e3ba2.png)

`adversarial_representation=False` 
![image](https://cloud.githubusercontent.com/assets/6783835/20518324/10d17aa2-b09f-11e6-9181-57ace19f8d1b.png)

**Comment by pgermain** [comment]
Thanks @pmorerio for raising this. With some combinations of datasets/parameters, the adversarial component has more or less influence on the final result. Note also that the experiment results on the paper are not necessarily obtained with the same parameters (but chosen by the *reverse validation* procedure) for DANN and standard NN. 

I changed the default example parameters to present a case where the adversarial component is more effective.
