### ISSUE TITLE
How do you create no. of trials of the experiment_amazon.py ?

### ISSUE THREAD

**Issue by debasmitdas** [GRAAL-Research/domain_adversarial_neural_network#3]
From the script, it seems that you have used all the xs, xt, xtest for one realization of the experiment. How did you realize different trials or in other words, how did you split your data and report avg. and std. accuracy in your paper ? Kindly explain.

**Comment by pgermain** [comment]
For this experiment, we did not realize multiple trials (see Table 1a of [the paper](http://jmlr.org/papers/v17/15-239.html)). Instead, we compute the Pairwise Poisson binomial test using the 12 different tasks (as reported by Table 1b). That is, we use the exact same splits provided in the [data folder](https://github.com/GRAAL-Research/domain_adversarial_neural_network/tree/master/data) of the repository, and loaded by the [load_amazon function](https://github.com/GRAAL-Research/domain_adversarial_neural_network/blob/4f04bd1024d924e0d844a4a6652ce0612e256976/experiments_amazon.py#L71).
