### ISSUE TITLE
Why the test files have labels?

### ISSUE THREAD

**Issue by wenhuazang** [GRAAL-Research/domain_adversarial_neural_network#4]
Thanks for sharing your code! However, i don't know why the unlabeled data in the raw data is labeled in your test.svmlight file. In other words, the test.svmlight files should not have labels. Could you please explain it.

**Comment by pgermain** [comment]
The test labels are used solely to compute the **test risk**, and are not seen by the learning algorithm during the training process.

**Comment by wenhuazang** [comment]
For each domain, there are 2,000 labeled reviews and approximately 4,000 unlabeled reviews (varying slightly across domains) and the classes are balanced. Why  'the 4, 000 unlabeled reviews' has label in your test data?

**Comment by jeanfrancisroy** [comment]
Just to understand your issue better: why are you surprised that there are labels **available** in the data? For the same reason that there are labels associated with the test data points, all of Amazon's original data is annotated with labels. There is no need to delete values in the data files if the program that reads the data is reading the parts that it needs to perform the experimentation. As an example, another algorithm might want to use the labels to perform an experiment in the inductive setting using the same source of data (we wouldn't need to copy the data around and remove/add values in it, the algorithm can read what it needs).

The part that you need to look at is the `load_amazon` function that loads the data, but especially the place where the function is called. You will see that the target (unlabeld) data's labels are not used.

**Comment by don-tpanic** [comment]
Hey @jeanfrancisroy, 
I wonder if you have or can kindly point me to the amazon dataset with all the data annotated with labels? I am aware the data used in this paper is fully labeled but I have been trying to find a dataset in which the data has not been preprocessed, which I can only find it here http://www.cs.jhu.edu/~mdredze/datasets/sentiment/. But it seems there's a part it is not labeled.

**Comment by jeanfrancisroy** [comment]
This seems to be the right repository - `unprocessed.tar.gz` contains everything that was originally used to build the processed versions of these datasets, by the first authors using this data.

`all.review` seem to contain XML with the product's name, the rating title, description and number of stars, etc. According to the webpage you cited, negative/positive/unlabeled.review are only one possible split, but it does look like they are only a split from `all.review` that has all the stuff.
