### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by don-tpanic** [GRAAL-Research/domain_adversarial_neural_network#7]
Hi,
I was unable to create the same amazon data that has already been kindly provided in this repo. I have tried to extract unigram and bigram features from the raw data (the most frequent 5k) yet the result is far from being the same as yours. I have also checked the Chen 2012 paper which you referred to. However the preprocessing step was mentioned in that paper rather obscurely. I wonder can you please explain how exactly were the data being preprocessed?

Thank you.

**Comment by pgermain** [comment]
Hi,
We simply used the dataset provided on Chen's website: 
https://www.cse.wustl.edu/~mchen/code/mSDA.tar

The dataset file is in matlab. I converted it in svmlight format and generated random train/test splits using the following python script:

```
import numpy as np
import scipy.io
from sklearn.datasets import dump_svmlight_file
from sklearn.utils import shuffle

domains_list = ['books', 'dvd', 'electronics', 'kitchen']
out_folder = 'datasets/'

orig = scipy.io.loadmat('matlab/examples/amazon.mat')
X_all = orig['xx'][:5000,:].T
Y_all = orig['yy'].T[0]
m = np.shape(X_all)[0]

offsets_list = list( orig['offset'].T[0] ) + [m]

random_state = 43
for i, domain_name in enumerate( domains_list ):
    print domain_name
    first, last = offsets_list[i], offsets_list[i+1] 
    
    X_train = X_all[first:first+2000,:]
    Y_train = Y_all[first:first+2000]
    X_train, Y_train = shuffle(X_train, Y_train, random_state=random_state)
    random_state += 1
    
    X_test = X_all[first+2000:last,:]    
    Y_test = Y_all[first+2000:last]    
    X_test, Y_test = shuffle(X_test, Y_test, random_state=random_state)
    random_state += 1
        
    dump_svmlight_file(X_train, Y_train, out_folder + domain_name + '_train.svmlight')
    dump_svmlight_file(X_test, Y_test, out_folder + domain_name + '_test.svmlight')
```
